### ISSUE TITLE
Cannot upload files (Max Size: 0B)

### ISSUE THREAD

**Issue by joshuaavalon** [directus/docker#14]
**docker-compose.yml**
```yml
version: "3"

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "somedb"
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_USER: "someusername"
      MYSQL_PASSWORD: "somepassword"
    ports:
      - 3306:3306
  api:
    image: directus/api:latest
    environment:
      DATABASE_HOST: database
      DATABASE_NAME: "somedb"
      DATABASE_USERNAME: "someusername"
      DATABASE_PASSWORD: "somepassword"
      ADMIN_EMAIL: "admin@localhost.com"
      ADMIN_PASSWORD: "directusrocks"
    ports:
      - 7000:80
  app:
    image: directus/app:latest
    environment:
      API_ENDPOINT: "API; http://192.168.1.187:7000/_/"
    ports:
      - 8000:80
```

If I send a get request to `http://192.168.1.187:7000/_/`, I get
```json
{
  "data": {
    "api": {
      "version": "2.0.13",
      "database": "mysql"
    },
    "server": {
      "max_upload_size": 2097152,
      "general": {
        "php_version": "7.2.13",
        "php_api": "fpm-fcgi"
      }
    }
  }
}
```

However,

![directus](https://user-images.githubusercontent.com/7152420/50562720-6cc6f100-0d51-11e9-8037-8d2af467d661.PNG)

Potential problem(?)

There are two errors in network tab.

1. OPTIONS 405 on `http://192.168.1.187:7000/`
My guess is it should be `http://192.168.1.187:7000/_/` instead. There is some error on rewrite which make the app cannot get configuration.

2. GET 500 on `http://192.168.1.187:7000/_/users/me?fields=last_page`
I don't think this is the problem.

**Comment by joshuaavalon** [comment]
Some update. The problem seems to be `directus/api`. If I point the api address to the demo one, there aren't any error.

**Comment by stormbyte** [comment]
I changed 
`try_files $uri $uri/ /index.php$is_args$args;`
 to 
`try_files _ /index.php$is_args$args;`

This seems to work for now but routing all calls to php and not trying to serve the file directly.
File: `rootfs/etc/nginx/conf.d/default.conf`

**Comment by stormbyte** [comment]
And for fixing the js and css files
```
    location ~ \extentions/ {
	try_files $uri $uri/ /index.php$is_args$args;
    }
```
above
```
location ~ / {
        try_files _ /index.php$is_args$args;
```

**Comment by joshuaavalon** [comment]
@stormbyte What does `try_files _` actually do? I cannot find it anywhere?

**Comment by Felix-IR** [comment]
> And for fixing the js and css files
> 
> ```
>     location ~ \extentions/ {
> 	try_files $uri $uri/ /index.php$is_args$args;
>     }
> ```
> above
> 
> ```
> location ~ / {
>         try_files _ /index.php$is_args$args;
> ```

Doesn't helped me, getting following error 
```
{
    "error": {
        "error": 8,
        "message": "API Environment Configuration Not Found: extensions"
    }
}
```

**Comment by stormbyte** [comment]
@joshuaavalon the `try_files _` forces the fallback `/index.php$is_args$args;` to be parsed

The solution is not yet complete as I now missing some css.
`extensions/core/layouts/tabular/layout.css`
This file does not exist inside the image

**Comment by WoLfulus** [comment]
Can you guys confirm that this is fixed on my last commit?

Thanks!

**Comment by rwatts3** [comment]
Hi unfortunately I don't think the latest image was built.
Docker hub shows the images were updated 2 months ago.
And I just docker pulled, nothing came down, and it's the same image.

**Comment by rwatts3** [comment]
Correction, I see docker/api was updated 4 hours ago, however the problem is still the same.

**Comment by stormbyte** [comment]
For some reason I don't get the updated version from docker hub.
manualy updated the `default.conf` it does seem to fix the `Max Size: 0B` As i can upload images and see the thumbs.

**Comment by WoLfulus** [comment]
Hey!

Yesterday I failed to make a proper build of the images and it ended up without any changes. 
I manually triggered the build again now.

Can you guys please pull the images again and make a new test?

Thanks!

**Comment by stormbyte** [comment]
Have pulled the changes and see the update.
First tests work, nice job

**Comment by beac0n** [comment]
This bug reappeared with the latest docker image (2.0.15), but it is fixed in 2.0.13.

It is really frustrating to not being able to update the api to the latest docker image, without fearing that an alrady closed bugs will reappear.

**Comment by WoLfulus** [comment]
@beac0n I'll need to check what changed from .13 to .15

We're in the process of rethinking the repository structure itself, the release pipeline and in this process I'll find a way to make tests on the docker image itself each release we make before pushing to docker hub so we can avoid bugs related to docker image itself.

Sorry about that :(

**Comment by mvhirsch** [comment]
I cannot reproduce this issue in .18. Anyone can please confirm?

**Comment by shartley76** [comment]
we have the same issue with v2.0.18 of the API running on Docker. Interestingly when running container locally and in our test environment, we get the correct max_upload_size displayed in the file upload dialogue (in our case 500Mb). However when deploying the same image to production, we get the 0 B issue. 
The difference in test vs. prod is that we have the api and app on seperate EC2 instances in AWS, however other API operations succeed (such as viewing/adding a collection) in this deployment format.

**Comment by WoLfulus** [comment]
Please let me know if this still persists on latest images we published. I'm closing this for now.

**Comment by beac0n** [comment]
We migrated away from directus. Not particularly because of this issue, but because of the software quality in general. There were just too many issues we had to deal with.
